export const CHUNKS: string[] = [
  // ── Parvas ────────────────────────────────────────────────────────────────
  "Adi Parva is the first book of the Mahabharata. It covers the origins of the Kuru dynasty, the birth of the Pandavas and Kauravas, early life, education under Drona, the house of lac, and Draupadi's swayamvara where Arjuna wins her hand.",

  "Sabha Parva is the second book. It describes the dice game orchestrated by Shakuni where Yudhishthira loses everything — his kingdom, his brothers, himself, and finally Draupadi. Draupadi's public humiliation when Dushasana attempts to disrobe her becomes the true catalyst of the war. The Pandavas are exiled for 13 years.",

  "Vana Parva (Aranyaka Parva) is the third book covering the Pandavas' 12 years in the forest. It contains the Yaksha Prashna where Yudhishthira answers riddles to revive his brothers, Arjuna's penance to obtain divine weapons from Indra and Shiva, and many sub-stories including the tale of Nala and Damayanti.",

  "Virata Parva is the fourth book. The Pandavas spend their 13th year in disguise at King Virata's court. Yudhishthira becomes a dice teacher, Bhima a cook, Arjuna (as Brihannala) a dance teacher, Draupadi a maid. Kichaka, who harasses Draupadi, is killed by Bhima. Their identities are nearly revealed when Arjuna fights the Kuru army alone.",

  "Udyoga Parva is the fifth book covering the preparations for war. Krishna undertakes a peace mission to Hastinapura on behalf of the Pandavas, asking only five villages. Duryodhana refuses even a needlepoint of land. Both sides gather armies. Karna is revealed to be Kunti's son by Krishna, who asks him to switch sides; Karna refuses out of loyalty to Duryodhana.",

  "Bhishma Parva is the sixth book covering the first 10 days of the Kurukshetra war, with Bhishma as commander of the Kaurava forces. It contains the Bhagavad Gita in full — Krishna's divine counsel to the grief-stricken Arjuna who refuses to fight. Bhishma is eventually brought down on the tenth day using Shikhandi as a shield, since Bhishma had vowed never to fight someone who was once a woman.",

  "Drona Parva covers days 11 through 15 of the war with Dronacharya as Kaurava commander. The most devastating loss is Abhimanyu's death — Arjuna's son, who knew how to enter the Chakravyuha formation but not how to exit. He is killed by multiple warriors simultaneously in violation of the rules of war. Arjuna vows to kill Jayadratha by sunset the next day or immolate himself. Krishna hides the sun using his Sudarshana Chakra, tricks Jayadratha into revealing himself, and Arjuna kills him. Drona is killed through deception — Yudhishthira tells him 'Ashvatthama is dead,' causing Drona to lower his weapons in grief, after which Dhrishtadyumna beheads him.",

  "Karna Parva covers days 16 and 17 with Karna as Kaurava commander. Karna fights brilliantly but faces accumulated misfortunes — his chariot wheel sinks into the earth (curse of Parashurama for being lowborn), he forgets the Brahmastra mantra (another curse), and Shalya as his charioteer actively demoralizes him. Arjuna kills Karna while his wheel is stuck — a moment of adharma that haunts the Pandavas.",

  "Shalya Parva covers the 18th and final day of war. Shalya becomes the last Kaurava commander. Duryodhana, the last survivor among the Kauravas, hides in a lake. He is goaded into fighting Bhima with maces. Bhima breaks Duryodhana's thighs — a blow below the waist, technically against the rules — fulfilling his vow. Duryodhana dies cursing the Pandavas.",

  "Sauptika Parva describes Ashvatthama's night massacre after the war. Enraged by his father Drona's death through deception, Ashvatthama enters the sleeping Pandava camp with Kripa and Kritavarma. He slaughters Dhrishtadyumna, Shikhandi, and all five sons of the Pandavas (the Upapandavas). He then uses the Brahmastra against Uttara's womb to kill the last Pandava heir. Arjuna counters with his own Brahmastra. The sages intervene — Ashvatthama's weapon, unable to be recalled, is redirected but still kills the unborn child Parikshit. Vyasa later revives Parikshit. Ashvatthama is cursed by Krishna to wander the earth for 3,000 years in agony.",

  "Stri Parva covers the lamentation of the women after the war. Gandhari, having lost all 100 sons, unleashes a curse on Krishna — that he will see his own kin destroy each other just as she has. Krishna accepts the curse with composure, knowing it is just.",

  "Shanti Parva is the longest single book. Bhishma, lying on his bed of arrows waiting for the auspicious moment to die, delivers vast teachings on dharma, statecraft, the duties of kings, moksha, and the nature of the self. Yudhishthira, overcome with guilt over the war's destruction, is counseled by both Krishna and Bhishma.",

  "Anushasana Parva continues Bhishma's teachings on ethics, the importance of truth, the nature of gifts and generosity, and the duties of individuals in society. Bhishma finally dies when the sun moves to the auspicious northern solstice.",

  "Ashvamedhika Parva describes Yudhishthira's horse sacrifice to purify the kingdom after the war. Arjuna follows the sacrificial horse across kingdoms, fighting kings who refuse to submit. Arjuna encounters his own grandson Babruvahana, who kills him — Arjuna is later revived by a Naga.",

  "Ashramavasika Parva: Dhritarashtra, Gandhari, and Kunti retire to the forest as ascetics. They die in a forest fire. Vidura also dies during this period.",

  "Mausala Parva describes the destruction of the Yadava clan 36 years after the war. A curse by sages causes the Yadavas to fight among themselves with reeds that become weapons. Krishna's son Pradyumna and brother Balarama also die. Krishna himself is killed by a hunter named Jara who mistakes his foot for a deer. This fulfills Gandhari's curse.",

  "Mahaprasthanika Parva: The five Pandavas and Draupadi renounce the kingdom and begin their final journey north toward the Himalayas and Mount Meru. One by one, Draupadi and four of the Pandavas fall and die. Each death corresponds to a flaw — Draupadi favored Arjuna too much, Nakula and Sahadeva were proud of their beauty and knowledge, Bhima was a glutton, Arjuna was too proud of his archery. Only Yudhishthira completes the ascent.",

  "Svargarohana Parva: Yudhishthira reaches heaven with a dog who has followed him throughout. He refuses to enter heaven without the dog. The dog is revealed to be Dharma — his own father, testing him. In heaven, he first sees the Kauravas enjoying paradise and is told the Pandavas are in hell — another test. He insists on joining his brothers in hell rather than enjoying heaven alone. This act of loyalty causes the illusion to dissolve. All are revealed to be in their true forms of peace.",

  // ── Key Characters ──────────────────────────────────────────────────────────
  "Yudhishthira (also called Dharmaraja) is the eldest Pandava, son of the god Dharma and Kunti. He is known for absolute truthfulness — his chariot wheels always floated above the earth because of his virtue. Yet his gambling addiction was his fatal flaw. He lost everything in the dice game. His one lie — telling Drona that Ashvatthama was dead (true of the elephant, not the man) — caused Drona's death and lowered his chariot to the ground. He was often passive and consumed by guilt but ultimately the most morally complex Pandava.",

  "Bhima is the second Pandava, son of Vayu the wind god and Kunti. He is the strongest of the five, fiercely loyal, and somewhat impulsive. He made three famous vows: to kill all 100 Kauravas, to drink Dushasana's blood, and to break Duryodhana's thighs. He kept all three. He killed Hidimba, Baka, Kichaka, and Jarasandha. He is the one who most feels the weight of the war's horror — weeping openly after killing Duryodhana, whom he had hated and loved like a brother.",

  "Arjuna is the third Pandava, son of Indra the king of gods and Kunti. He is the greatest archer of the age. His bow is called Gandiva, his quiver is inexhaustible, and his charioteer is Krishna himself. He won Draupadi's hand at the swayamvara by stringing a mighty bow and shooting a rotating fish target while looking only at its reflection. He is peerless in skill but deeply prone to doubt and grief — the Bhagavad Gita arises precisely because he collapses on the battlefield, refusing to fight his own kin.",

  "Nakula is the fourth Pandava, twin of Sahadeva, son of the divine physician twins the Ashvins and Madri. He is considered the most handsome man of his age and is an expert in horsemanship and swordsmanship. His pride in his beauty was his flaw, for which he fell during the final journey.",

  "Sahadeva is the fifth Pandava, twin of Nakula. He is gifted with knowledge of astrology and prophecy — he knew the war would happen but was bound by a curse not to reveal it unless asked. His flaw was pride in his knowledge. He is said to have consumed a portion of Pandu's flesh after his father's death, which gave him the power of foresight.",

  "Duryodhana is the eldest of the 100 sons of the blind king Dhritarashtra and Gandhari. He is brave, generous to his allies, and genuinely gifted as a warrior and leader. His fatal flaw was consuming envy of the Pandavas — particularly Bhima. He could not tolerate that others received what he believed was rightfully his. He was not purely villainous: he honored Karna when the entire world rejected him for being lowborn, and remained loyal to his friends. He died refusing to admit defeat, calling his life a success because he died as a king and a warrior.",

  "Karna (also called Radheya and Vasusena) is the most tragic figure of the Mahabharata. He was born to Kunti and the sun god Surya before her marriage to Pandu. Terrified of shame, Kunti placed him in a basket on the river. He was found and raised by a charioteer named Adhiratha and his wife Radha, whose name he took. He was denied education by Drona for being lowborn. He was publicly humiliated at a tournament where he tried to compete with Arjuna. Duryodhana alone stepped forward, crowned him King of Anga, and became his lifelong friend. This act of friendship bound Karna to the Kaurava cause despite knowing it was wrong. He gave away his divine armor and earrings to Indra in disguise, knowing it would seal his death. He was told his true identity by Krishna and by Kunti on the eve of war — but chose loyalty to Duryodhana over survival.",

  "Krishna (also called Vasudeva, Govinda, Madhava) is the avatar of Vishnu and the supreme being of the Mahabharata. He is cousin to both the Pandavas and the Kauravas through his Yadava lineage. When both sides came to him before the war, he offered a choice: his entire army, or himself alone unarmed. Duryodhana took the army. Arjuna chose Krishna. Krishna became Arjuna's charioteer. His role is deeply paradoxical: he counsels non-attachment to outcome while being the war's supreme strategist. He engineered several technically adharmic killings — using Shikhandi against Bhishma, allowing Karna to be killed while unarmed, arranging the lie about Ashvatthama — because he understood that in this war, pure dharma against superior adharma would lose.",

  "Draupadi (also called Panchali and Krishnaa) was born fully grown from a sacred fire along with her brother Dhrishtadyumna, with the explicit purpose of bringing about the destruction of the Kuru dynasty. She is the wife of all five Pandavas. Her swayamvara required stringing an impossibly heavy bow and shooting a rotating fish target — only Arjuna succeeded. Her humiliation in the Sabha court — dragged by her hair by Dushasana while Bhishma, Drona, and Vidura watched silently — is the true moral wound of the epic. Her unanswered question 'Was I won as property or as a free person?' remains one of the Mahabharata's greatest unresolved challenges to patriarchy.",

  "Bhishma (born Devavrata) is the son of King Shantanu and the goddess Ganga. He took a terrible oath — the Bhishma Pratigya — to never marry and never claim the throne, so his father could marry the fisherman's daughter Satyavati. He was granted the boon of choosing his own moment of death (iccha mrityu). He served as commander of the Kaurava forces for the first 10 days. He fought for a cause he knew was unjust because his oath bound him to the throne of Hastinapura, not to its occupant. He lay on a bed of arrows for 58 days, waiting for the auspicious moment, and in that time delivered the vast teachings that form the Shanti and Anushasana Parvas.",

  "Drona (Dronacharya) was the preceptor of both the Pandavas and Kauravas in all martial arts. He was the son of the sage Bharadvaja. In poverty, he went to his childhood friend Drupada for help and was publicly humiliated. He vowed revenge and trained Arjuna specifically to defeat Drupada. He demanded Ekalavya's right thumb as guru dakshina to protect Arjuna's supremacy — one of the epic's most debated moments. He fought for the Kauravas out of obligation to the throne. He was killed through a half-truth — he was invincible in battle but put down his weapons upon hearing (falsely) that his son Ashvatthama was dead.",

  "Kunti (born Pritha) is the mother of Yudhishthira, Bhima, and Arjuna. As a young woman she was given a mantra by the sage Durvasa that could invoke any god to father her child. Testing it, she called upon Surya and bore Karna — whom she set adrift in a basket out of shame. She later used the mantra three times as the wife of Pandu. Her greatest burden was her secret: she knew Karna was her firstborn. She told him this on the eve of the war, promising she would not lose more than five sons total — but this pledge protected only Arjuna, not Karna.",

  "Gandhari is the wife of the blind king Dhritarashtra. When she learned she was to marry a blind man, she blindfolded herself and wore the blindfold for the rest of her life to share his darkness. She is the mother of 100 sons — the Kauravas — born from a divine boon. After the war, she confronted Krishna, accusing him of having the power to prevent it. She cursed him that he would watch his own clan destroy itself. Krishna accepted the curse fully, saying it was just.",

  "Ashvatthama is the son of Drona and one of the seven chiranjeevis (immortals) of Hindu tradition. After his father's death through deception, he committed the night massacre of the sleeping Pandava camp, killing all the Upapandavas. He used the Brahmastra against Uttara's unborn child. Krishna cursed him to wander the earth for 3,000 years, his wounds festering and unhealing, as penance for attacking the unborn.",

  "Ekalavya was a Nishada (tribal) boy who idolized Drona but was refused as his student because of his low caste. He built a clay statue of Drona and taught himself archery through devotion, becoming arguably the finest archer of his age. When Drona discovered this and demanded his right thumb as guru dakshina — a demand designed to protect Arjuna's supremacy — Ekalavya gave it without hesitation. His story is the Mahabharata's sharpest critique of caste hierarchy.",

  "Vidura is the half-brother of Dhritarashtra and Pandu, born of the sage Vyasa and a maidservant. He is known as the wisest man in Hastinapura. He consistently warned Dhritarashtra against Duryodhana's adharma, counseled the Pandavas, and tried to prevent the dice game. He is considered a partial incarnation of Dharma. He was powerless to stop what he could foresee.",

  "Shakuni is the maternal uncle of Duryodhana, brother of Gandhari. He is the master manipulator of the Mahabharata, the architect of the dice game. His motivation is revenge against the Kuru dynasty for what they did to his family in arranging Gandhari's marriage to a blind man. His loaded dice are the weapon that undoes the Pandavas without a single arrow being fired.",

  // ── Bhagavad Gita ───────────────────────────────────────────────────────────
  "The Bhagavad Gita consists of 18 chapters and 700 verses (shlokas). It takes place on the battlefield of Kurukshetra, in the middle of both armies, just before the war begins. Arjuna, seeing his teachers, uncles, and cousins arrayed against him, collapses in grief and refuses to fight. Krishna's response to this collapse forms the entire Gita.",

  "Bhagavad Gita Chapter 1 (Arjuna Vishada Yoga — The Yoga of Arjuna's Grief): Arjuna surveys the battlefield and is overcome with grief. He sees Bhishma, Drona, his cousins, and teachers. He tells Krishna he cannot fight and kill his own kin for the sake of a kingdom. He drops his bow Gandiva and sinks into his chariot.",

  "Bhagavad Gita Chapter 2 (Sankhya Yoga — The Yoga of Knowledge): Krishna begins his teaching. He tells Arjuna the soul is eternal and cannot be killed — 'never was there a time when I did not exist, nor you, nor all these beings; nor in the future shall any of us cease to be.' He introduces the concept of the eternal self (atman) vs the perishable body. He teaches nishkama karma — action without attachment to results. The famous verse 2.47: 'You have a right to perform your prescribed duties but never to the fruits of your actions.'",

  "Bhagavad Gita Chapter 3 (Karma Yoga — The Yoga of Action): Krishna teaches that inaction is not possible — even breathing is action. One must act according to one's svadharma (personal duty). It is better to perform one's own duty imperfectly than another's duty perfectly. Action done as sacrifice (yajna), without ego and without desire for results, does not bind the soul.",

  "Bhagavad Gita Chapter 4 (Jnana Karma Sanyasa Yoga): Krishna reveals that the Gita's teaching is ancient — he taught it to the sun god Vivasvan at the beginning of time. He explains the doctrine of divine incarnation: 'Whenever dharma declines and adharma rises, I manifest myself. I am born age after age to protect the good, destroy the wicked, and re-establish dharma.' He teaches that all actions can be offered as sacrifice to the divine.",

  "Bhagavad Gita Chapter 5 (Karma Sanyasa Yoga): Krishna reconciles renunciation with action. The true renunciate acts in the world but is inwardly unattached. The wise see the same Self in a learned Brahmin, a cow, an elephant, a dog, and an outcaste. The enlightened one neither rejoices in pleasure nor grieves in pain.",

  "Bhagavad Gita Chapter 6 (Dhyana Yoga — The Yoga of Meditation): Krishna teaches the practice of meditation — controlling the mind, sitting in a clean place, focusing awareness. The mind is both the greatest friend and the greatest enemy of the self. He describes the qualities of the yogi who has realized the Self. Arjuna asks what happens to someone who begins the path but doesn't complete it — Krishna assures him no spiritual effort is ever lost.",

  "Bhagavad Gita Chapter 7 (Jnana Vijnana Yoga): Krishna reveals his divine nature. He is the taste in water, the light in the moon and sun, the sacred syllable Om. His lower nature is the eight material elements; his higher nature is the life force in all beings. Few among thousands seek him; fewer still truly know him.",

  "Bhagavad Gita Chapter 8 (Aksara Brahma Yoga): Krishna teaches about death and what determines the next birth. Whatever one thinks of at the moment of death, that is what one becomes. He describes the path of light (northern path) and the path of darkness (southern path), and the ultimate liberation — never returning to rebirth.",

  "Bhagavad Gita Chapter 9 (Raja Vidya Raja Guhya Yoga — The Royal Secret): Krishna reveals the most confidential knowledge. He sustains all beings but is not in them — as the vast wind moves in space yet space is not the wind. He accepts any offering made with love — a leaf, a flower, fruit, or water. He promises that his devotees will never perish.",

  "Bhagavad Gita Chapter 10 (Vibhuti Yoga — The Yoga of Divine Manifestations): Krishna describes his divine manifestations. He is the beginning, middle, and end of all beings. Among the Vedas he is the Sama Veda; among mountains, the Meru; among rivers, the Ganga; among warriors, Rama; among fish, the shark; among letters, the letter A. He is the gambling of cheats and the splendor of the splendid.",

  "Bhagavad Gita Chapter 11 (Vishvarupa Darshana Yoga — The Vision of the Universal Form): Arjuna asks to see Krishna's cosmic form. Krishna grants him divine sight. Arjuna sees a terrifying, infinite form — all of creation and destruction simultaneously, with countless mouths and eyes, blazing like a thousand suns. He sees the warriors already being swallowed. He asks: who are you? Krishna replies: 'I am Time, the great destroyer of worlds. Even without you, all the warriors standing arrayed in the opposing armies shall cease to exist.' Arjuna begs Krishna to return to his gentle human form.",

  "Bhagavad Gita Chapter 12 (Bhakti Yoga — The Yoga of Devotion): Krishna declares devotion (bhakti) the most direct path to him. Those who worship him with loving devotion, fixing their minds on him, he personally carries what they lack and preserves what they have. He describes the qualities of the devotee: free from hatred, friendly and compassionate to all, free from possessiveness, equal in joy and sorrow, forgiving.",

  "Bhagavad Gita Chapter 13 (Kshetra Kshetrajna Vibhaga Yoga): Krishna distinguishes between the field (the body and all material experience) and the knower of the field (the conscious self). True knowledge is humility, non-violence, patience, seeing the same Self in all beings, devotion to the teacher, and perceiving the unchanging amidst the changing.",

  "Bhagavad Gita Chapter 14 (Gunatraya Vibhaga Yoga): Krishna explains the three gunas — tamas (inertia, darkness), rajas (passion, activity), sattva (clarity, goodness). All beings in the material world are bound by these three qualities. Sattva binds through happiness and knowledge; rajas through desire and action; tamas through negligence and sleep. Liberation means transcending all three.",

  "Bhagavad Gita Chapter 15 (Purushottama Yoga — The Supreme Person): Krishna describes the cosmic tree of existence — rooted above (in the divine), branches below (in the material world). The wise cut this tree with the weapon of non-attachment. There are two beings in the world: the perishable and the imperishable. Beyond both is the Supreme Person — the Purushottama — who pervades and sustains all three worlds.",

  "Bhagavad Gita Chapter 16 (Daivasura Sampad Vibhaga Yoga): Krishna distinguishes divine qualities (fearlessness, purity, compassion, truthfulness, non-violence, freedom from anger and greed) from demonic qualities (hypocrisy, arrogance, pride, harshness, ignorance). Those with demonic nature act from ego, believing there is no truth beyond the material.",

  "Bhagavad Gita Chapter 17 (Shraddhatraya Vibhaga Yoga): Krishna describes three types of faith corresponding to the three gunas. Sattvic faith worships the divine; rajasic faith worships power and wealth; tamasic faith worships spirits and the dead. Actions, food, sacrifice, and austerity are all categorized by the three gunas.",

  "Bhagavad Gita Chapter 18 (Moksha Sanyasa Yoga — Liberation through Renunciation): The final and longest chapter. Krishna summarizes all his teachings. He distinguishes true renunciation (giving up the fruits of action) from mere abandonment (giving up action itself). He reveals the four-fold division of society based on nature and duty. He concludes with the most radical verse — 18.66: 'Abandon all varieties of dharma and surrender unto Me alone. I shall deliver you from all sinful reactions; do not fear.' Arjuna's confusion dissolves. He declares he will fight.",

  // ── Philosophy ─────────────────────────────────────────────────────────────
  "Dharma in the Mahabharata is not a fixed law but a living, contested question. The Sanskrit root means 'that which upholds' — the right order of things. Every character in the Mahabharata is in conflict with dharma. Bhishma's dharma of loyalty to the throne conflicts with his personal sense of justice. Karna's dharma of friendship to Duryodhana conflicts with his duty to his true mother Kunti and to the Pandavas, his brothers. Yudhishthira's dharma of truth conflicts with the tactical necessity of a half-lie. The entire epic is a meditation on what dharma means when duties conflict with each other.",

  "Karma in the Mahabharata means action and its consequences across lives. The law of karma holds that every action creates a chain of cause and effect that ripples across time and lifetimes. The Bhagavad Gita offers a path through karma rather than around it: nishkama karma — acting without desire for results, performing one's duty as an offering to the divine, detached from the fruits. This does not mean indifference to outcomes but freedom from being defined by them.",

  "Moksha means liberation from the cycle of birth, death, and rebirth (samsara). The Mahabharata presents multiple paths to moksha: jnana (knowledge), karma (action), bhakti (devotion), raja yoga (meditation), and sankhya (discrimination between the real and unreal). The Shanti Parva contains Bhishma's extensive teachings on moksha from his deathbed — essentially a philosophical university compressed into one dying man's final words.",

  "Ahimsa (non-violence) is one of the highest values in Hindu philosophy, yet the Mahabharata shows that it must sometimes yield to kshatriya dharma — the warrior's duty. This is the central tension Krishna addresses in the Gita. A warrior who refuses to fight out of compassion is not practicing ahimsa but abandoning his duty. True ahimsa operates from wisdom, not sentiment — it asks what serves the greatest good, not merely what avoids immediate harm.",

  "Maya (illusion) is the veil that prevents beings from perceiving ultimate reality. In the Mahabharata, maya operates at every level: the illusion of the body as the self, the illusion of permanent possession, the illusion that victory in war means triumph. The dice game is a supreme symbol of maya — Yudhishthira believes he is wagering real things but is in fact gambling with shadows. Krishna's role is partly to pierce this veil — literally, by showing Arjuna the cosmic form in Chapter 11.",

  "The Yaksha Prashna is one of the most celebrated episodes in the Mahabharata. During the forest exile, four of the Pandavas drink from a lake and die after ignoring a mysterious voice's warning. Yudhishthira approaches and the voice — the Yaksha — demands he answer questions before drinking. Yudhishthira answers every question correctly. 'What is swifter than the wind?' — The mind. 'What is more numerous than grass?' — Thoughts. 'What is the greatest wonder?' — Every day people die, yet those who remain live as if they are immortal. The Yaksha is revealed to be Dharma — Yudhishthira's divine father.",

  "The dice game (dyuta) in Sabha Parva is engineered by Shakuni using loaded dice. Yudhishthira cannot stop gambling even as he loses everything. The cosmic implication is that maya — the power of illusion and desire — can bind even the most virtuous soul. After losing the kingdom, his brothers, and himself, Yudhishthira stakes Draupadi. The question that arises — whether a man who has already lost himself can stake another person — is never legally resolved in the text. Draupadi's resilience in that moment is what preserves the Pandavas' dignity.",

  "The concept of svadharma (one's own duty) vs paradharma (another's duty) is central to the Gita. Krishna teaches that it is better to perform one's own duty imperfectly than another's duty perfectly, because following another's path leads to spiritual danger. Arjuna's svadharma as a kshatriya is to fight — his compassion, however noble it appears, is paradharma in this context. The Mahabharata pushes this further: svadharma is not merely occupational but cosmic — each soul has a unique path.",

  "The Kurukshetra war lasted 18 days and resulted in the near-total annihilation of the kshatriya class. Both sides violated the rules of war repeatedly: fighting at night, attacking the unarmed, using weapons against a single warrior simultaneously. The Mahabharata's moral is not that war is glorious — it is that war destroys everything, including the victors. The Pandavas won but inherited a kingdom emptied of allies, their children massacred, their enemies all dead. Yudhishthira's guilt was so profound he initially refused to rule.",

  "The Bhagavad Gita's teaching on the eternal soul (atman): Krishna tells Arjuna that the soul is birthless, deathless, and changeless. Weapons cannot cut it, fire cannot burn it, water cannot wet it, wind cannot dry it. It is ancient, unborn, and does not die when the body dies. Just as a person discards old clothes and puts on new ones, the soul discards old bodies and takes on new ones. This is the foundation of Krishna's argument that Arjuna should not grieve — the apparent death of those he loves is only the death of their bodies.",
];
